CVNClerkBot: Invoke generate in pywikibot dir
Otherwise:

```
$ python pywikibot-compat/generate_user_files.py
1: Create user_config.py file (required)
2: Create user_fixes.py file (optional, for advanced usage)
3: The two files
What do you do? Just enter the number: 1
Traceback (most recent call last):
  File "pywikibot-compat/generate_user_files.py", line 183, in <module>
    create_user_config('')
  File "pywikibot-compat/generate_user_files.py", line 69, in create_user_config
    os.path.join(base_dir, "families"))))
OSError: [Errno 2] No such file or directory: 'families'
```